project_id = "zqnjgwrvvrqaenzmlvfx"

[functions.admin-api]
verify_jwt = true

[functions.ai-task-assistant]
verify_jwt = false

[functions.create-demo-users]
verify_jwt = true

[functions.ingest-telemetry]
verify_jwt = false

[functions.ingest-events]
verify_jwt = false

[functions.mission-control]
verify_jwt = false

[functions.swarm-coordinator]
verify_jwt = false

[functions.detections-pipeline]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.get-weather]
verify_jwt = false

[functions.lang-detect]
verify_jwt = false

[functions.task-ai-assistant]
verify_jwt = false

[functions.translate]
verify_jwt = false

[functions.webhook-handler]
verify_jwt = false

[functions.jetson-vps-bridge]
verify_jwt = false

[functions.jetson-network-scanner]
verify_jwt = false
