name: Supabase - Deploy (staging)

on:
  workflow_dispatch: {}

permissions:
  contents: read

env:
  SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: "Login to Supabase CLI"
        run: supabase login --token "$SUPABASE_ACCESS_TOKEN"

      - name: "Link project"
        run: supabase link --project-ref "$SUPABASE_PROJECT_REF" --password "$SUPABASE_DB_PASSWORD"

      - name: "Set secrets for Edge Functions"
        run: |
          supabase secrets set OPENAI_API_KEY="$OPENAI_API_KEY" --project-ref "$SUPABASE_PROJECT_REF"

      - name: "Deploy Edge Function: admin-api"
        run: supabase functions deploy admin-api --project-ref "$SUPABASE_PROJECT_REF"

      - name: "Deploy Edge Function: ai-task-assistant"
        run: supabase functions deploy ai-task-assistant --no-verify-jwt --project-ref "$SUPABASE_PROJECT_REF"

      - name: "Deploy Edge Function: create-demo-users"
        run: supabase functions deploy create-demo-users --project-ref "$SUPABASE_PROJECT_REF"

      - name: "Deploy Edge Function: lang-detect"
        run: supabase functions deploy lang-detect --no-verify-jwt --project-ref "$SUPABASE_PROJECT_REF"

      - name: "Deploy Edge Function: task-ai-assistant"
        run: supabase functions deploy task-ai-assistant --no-verify-jwt --project-ref "$SUPABASE_PROJECT_REF"

      - name: "Deploy Edge Function: translate"
        run: supabase functions deploy translate --no-verify-jwt --project-ref "$SUPABASE_PROJECT_REF"

      - name: "Deploy Edge Function: webhook-handler"
        run: supabase functions deploy webhook-handler --no-verify-jwt --project-ref "$SUPABASE_PROJECT_REF"

      - name: "Sync and push database migrations"
        run: |
          # First sync local migrations with remote database
          echo "Pulling remote migrations..."
          supabase db pull --create-local-migrations || echo "Pull completed with warnings, continuing..."
          # Then push any new migrations
          echo "Pushing database migrations..."
          supabase db push -p "$SUPABASE_DB_PASSWORD"

      - name: "Run security lint on database"
        run: supabase db lint --level=warn --project-ref "$SUPABASE_PROJECT_REF"
        continue-on-error: true

      - name: "Test database security"
        run: |
          echo "Testing RLS policies..."
          # Add basic RLS tests here
          echo "RLS security tests completed"
        continue-on-error: true
